// Test the pure routing rules without dependencies or a browser.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const context = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../app.js'), 'utf8').split('// Shared localization')[0], context);
const state = (values, mode = 'Off-Grid') => JSON.parse(JSON.stringify(context.window.energyFlowState(values, mode)));
const base = { grid: 0, pv: 0, load: 500, battery: 0, soc: 20 };
assert.deepEqual(state({ ...base, grid: 500 }, 'Mains').routes, { gridHouse: true, solarHouse: false, batteryHouse: false, solarBattery: false });
assert.equal(state(base, 'Mains').batteryLabel, 'Waiting to charge');
assert.equal(state({ ...base, soc: 40 }, 'Mains').batteryLabel, 'Standby');
assert.equal(state({ ...base, soc: null }, 'Mains').batteryLabel, 'Standby');
assert.equal(state({ ...base, battery: null }, 'Mains').batteryLabel, 'No report');
assert.deepEqual(state({ ...base, pv: 1000, battery: 500 }).routes, { gridHouse: false, solarHouse: true, batteryHouse: false, solarBattery: true });
assert.deepEqual(state({ ...base, pv: 200, battery: -300 }).routes, { gridHouse: false, solarHouse: true, batteryHouse: true, solarBattery: false });
assert.deepEqual(state({ ...base, pv: 500, load: 0, battery: 500 }).routes, { gridHouse: false, solarHouse: false, batteryHouse: false, solarBattery: true });
assert.equal(state({ ...base, pv: 0, battery: -500 }).routes.batteryHouse, true);
assert.equal(state({ ...base, pv: null, grid: null }).routes.solarHouse, false);
assert.equal(state({ ...base, grid: 0.1 }).routes.gridHouse, false);
assert.equal(state({ ...base, battery: -0.1 }, 'Mains').batteryLabel, 'Waiting to charge');
assert.equal(state({ ...base, pv: 100, grid: 500 }).routes.solarHouse, false);
console.log('13 overview routing and battery-state assertions passed.');
const duration = context.window.energyFlowDuration;
for (const watts of [0, 100, 300, -500, null, NaN, Infinity]) assert.equal(duration(watts), 3);
assert.equal(duration(1150), 1.5);
assert.equal(duration(2000), 1);
assert.equal(duration(11000), 1);
for (let watts = 400; watts <= 2000; watts += 100) assert.ok(duration(watts) < duration(watts - 100));
assert.deepEqual(state({ ...base, pv: 1500, battery: 1000 }).routeWatts,
  { gridHouse: 0, solarHouse: 500, batteryHouse: 0, solarBattery: 1000 });
assert.equal(state({ ...base, battery: -1500 }).routeWatts.batteryHouse, 500);
assert.equal(state({ ...base, grid: 2000 }).routeWatts.gridHouse, 500);
assert.equal(state({ ...base, battery: 2500, pv: 2000 }).routeWatts.solarBattery, 2000);
console.log('31 power-based speed and per-route wattage assertions passed.');
